### ISSUE TITLE
The last fix did not propagate to ansible-galaxy

### ISSUE THREAD

**Issue by banezaklan** [itcraftsmanpl/ansible-role-php7#7]
Hey,
Looks like your latest fix for Debian did not propagate to ansible-galaxy.

**Comment by deuzu** [comment]
Temporary work around using a requirement file.

``` yml
- src: https://github.com/itcraftsmanpl/ansible-role-php7
  version: master
  name: itcraftsmanpl.php7
```
